name: Check Format and Lint
on:
  pull_request:
    
jobs:
  check-format-and-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: checkout
        uses: actions/checkout@v4

      # MEMO: このGHAがprojectの biome.json を参照してくれるならpnpmではなくこちらを使う
      # - name: setup-biome
      #   uses: biomejs/setup-biome@v2
      #   with:
      #     version: latest

      # - name: Run Biome
      #   run: biome ci

      # pnpm の使用のため
      - name: corepack enable
        run: corepack enable

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'pnpm'

      - name: pnpm clean install
        run: pnpm i --frozen-lockfile	


      - name: format and lint check
        run: pnpm run format-and-lint
