name: Check Build
on:
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: npm install
        run: npm ci

      - name: next build
        run: npm run build