name: Check Format and Lint
on:
  pull_request:
    
jobs:
  check-format-and-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: checkout
        uses: actions/checkout@v4

      # プロジェクト内の biome.json, package.json を参照して実行してくれる
      - name: setup-biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci
